# Generated by Django 4.2.15 on 2024-08-16 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=200, unique=True)),
                ('book_author', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField()),
                ('book_category', models.CharField(max_length=200)),
                ('book_description', models.CharField(max_length=200)),
                ('book_status', models.CharField(max_length=200)),
                ('book_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invApp.bookmodel')),
            ],
        ),
    ]
