# Generated by Django 4.2.15 on 2024-08-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
