# Generated by Django 4.2.15 on 2024-08-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0002_alter_bookmodel_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
